---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  pre_tasks:
    - setup:
        gather_subset:
          - user_dir
      tags: [ always ]
  roles:
  tasks:
  - import_tasks: tasks/vundle.yml
  - import_tasks: tasks/homebrew.yml
  - import_tasks: tasks/repos.yml
